### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by luemmel76** [fbolanos/LS7366R#1]
Hi,
after long search i found only your LS7366R python lib, but i'm missing the following features:

- check routine if the LS7366R is connected on on-board SPI or external SPI device (like the I2C routine in adafruits  
[MCP230xx.zip](https://github.com/fbolanos/LS7366R/files/1418441/MCP230xx.zip), line 33-41).

- the function for WRITE_DTR and LOAD_COUNTER

Hope you can add these two things

With best Regards
Thilo Brueckner
germany

**Comment by luemmel76** [comment]
Hi,
check routine is no longer needed because i use the LS direct on the RPi's SPI port.
With big help from an german python user the function for write DTR and load the counter is added.

With best Regards
Thilo Brueckner

**Comment by fbolanos** [comment]
Sorry I apologize for delayed reply! I have been really busy with my research lately. 
I am glad you are using this library. 
So write DTR and load counter are also good? 
Would you mind doing a pull request?
