### ISSUE TITLE
 Zero reading

### ISSUE THREAD

**Issue by mateusguilhermedasilva** [fbolanos/LS7366R#2]
Hello
I'm trying to read the encoder, but I always get 0 as encoder feedback. Already checked the connection of the wires and is correct.
I use pins 19,21,23 SPI.

I am also using a level shifter..

What did you do with the ls7366r "SS /" pin?

Any suggestion?

**Comment by fbolanos** [comment]
Apologies for late reply.
Did you manage to solve your issue?

Take a look at the datasheet, page 12. Do you have the LS7366R wired the same way?

As for your question about the SS pin this is what it does:

> **SS/ (Pin 4)** A  high  to  low  transition  at  the  SS/  (Slave  Select)  inputselects the LS7366R for serial bi-directional data transfer; alow to high transition disables serial data transfer and bringsthe MISO output to high impedance state. This allows for theaccommodation of multiple slave units on the serial I/O.

Best,

**Comment by mateusguilhermedasilva** [comment]
OK, problem solved I had to change pins on the raspberry.

**Comment by fbolanos** [comment]
Thank you Mateus! :)
